In [1]:
import numpy as np
array = np.array([3,33,333])
print(type(array))

<class 'numpy.ndarray'>


In [2]:
print(array.shape)

(3,)


In [5]:
print(array[0], array[1], array[2])

3 33 888


In [4]:
array[2] = 888

In [6]:
print(array)

[  3  33 888]


In [8]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)

[[1 2 3]
 [4 5 6]]


In [10]:
print(array2.shape)

(2, 3)


In [15]:
ex1 = np.zeros((3,3))
print(ex1)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [21]:
ex3 = np.full((4,3), 5.0)
print(ex3)

[[ 5.  5.  5.]
 [ 5.  5.  5.]
 [ 5.  5.  5.]
 [ 5.  5.  5.]]


In [24]:
ex4 = np.ones_like((1,5,3,3))
print(ex4)

[1 1 1 1]


In [27]:
ex5 = np.random.random((2,2))
print(ex5)

[[ 0.06238379  0.07052731]
 [ 0.50385685  0.53407209]]


In [49]:
#ex6 = np.ones((3,3,3))
print(ex6)

[[[ 7.  7.  7.]
  [ 7.  7.  7.]
  [ 7.  7.  7.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 7.  7.  7.]
  [ 7.  7.  7.]
  [ 7.  7.  7.]]]


In [35]:
ex6[1,1,1]

1.0

In [69]:
ex6[:,:,:] = 5
print(ex6)

[[[ 5.  5.  5.]
  [ 5.  5.  5.]
  [ 5.  5.  5.]]

 [[ 5.  5.  5.]
  [ 5.  5.  5.]
  [ 5.  5.  5.]]

 [[ 5.  5.  5.]
  [ 5.  5.  5.]
  [ 5.  5.  5.]]]


In [70]:
#slice = ex6[1,:,:]
print(slice)

[[ 5.  5.  5.]
 [ 5.  5.  5.]
 [ 5.  5.  5.]]


In [61]:
slice[:] = 2
print(slice)

[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


In [81]:
ex_array = np.array([[0, 1, 2, 3],
             [10,11,12,13],
             [20,21,22,23],
             [30,31,32,33]])
print(ex_array)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [71]:
col_indices = np.array([0,1,2,0])
print("col_indices: ", col_indices)
row_indices = np.arange(4)
print("row_indices: ", row_indices)

col_indices:  [0 1 2 0]
row_indices:  [0 1 2 3]


In [74]:
for i,j in zip(col_indices,row_indices):
    print(i,",",j)

0 , 0
1 , 1
2 , 2
0 , 3


In [83]:
print(ex_array[col_indices,row_indices])

[ 0 11 22  3]


In [85]:
ex_array[:2,]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [88]:
ex2_array = np.array(ex_array[:3,:2])
print(ex2_array)

[[ 0  1]
 [10 11]
 [20 21]]


In [90]:
filter = (ex2_array < 15)
print(filter)

[[ True  True]
 [ True  True]
 [False False]]


In [91]:
ex2_array[filter]

array([ 0,  1, 10, 11])

In [92]:
ex2_array[ex2_array < 15]

array([ 0,  1, 10, 11])

In [ ]:
ex2_array[(ex2_array < 15) & (ex2_array > 9)]

In [98]:
ex1.dtype

dtype('float64')

In [99]:
ex2 = np.array([12.4,43.3,2,34], dtype=np.int)
print(ex2)

[12 43  2 34]


In [101]:
arr = 10 + np.random.randn(2,5)
print(arr)

[[  7.90609144   9.75863404   7.39333202  11.31206885  10.72762571]
 [ 10.57706082  11.31511123   9.81490171  10.4638275   10.78452525]]


In [103]:
print(arr.mean())

10.0053178565


In [104]:
print(arr.mean(0))

[  9.24157613  10.53687263   8.60411686  10.88794817  10.75607548]


In [105]:
print(arr.mean(1))

[  9.41955041  10.5910853 ]


In [106]:
print(arr.sum())

100.053178565


In [108]:
print(np.median(arr, axis=1))

[  9.75863404  10.57706082]


In [109]:
unsorted = np.random.randn(10)
print(unsorted)

[ 0.32783359 -0.54169413  0.16023738  0.09697609 -0.77173661 -0.9621704
  1.45010523 -1.04076668  0.58711747  0.2489187 ]


In [111]:
sorted = np.array(unsorted)
sorted.sort()
print(sorted)

[-1.04076668 -0.9621704  -0.77173661 -0.54169413  0.09697609  0.16023738
  0.2489187   0.32783359  0.58711747  1.45010523]


In [112]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])

print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [113]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [114]:
print(np.setdiff1d(s1,s2))

['desk']


In [116]:
print(np.setdiff1d(s2,s1))

['lamp']


In [117]:
print(np.in1d(s1,s2))

[False  True  True]


In [119]:
start = np.zeros([4,3])
print(start)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [120]:
add_rows = np.array([1,2,3])
print(add_rows)

[1 2 3]


In [121]:
y = start+add_rows
print(y)

[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]


In [123]:
add_col = np.array([[1,2,3,4]])
add_col = add_col.T
print(add_col)

[[1]
 [2]
 [3]
 [4]]


In [124]:
x = start + add_col
print(x)

[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]
 [ 4.  4.  4.]]


In [125]:
add_scalar = np.array([1])
print(start + add_scalar)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [133]:
from timeit import Timer

size = int(1e6)
timeits = int(1e3)

print(size)
print(timeits)

1000000
1000


In [129]:
nd_array = np.arange(size)

print(type(nd_array))

<class 'numpy.ndarray'>


In [134]:
timer_np = Timer("nd_array.sum()","from __main__ import nd_array")
print(timer_np.timeit(timeits)/timeits)

0.005362167109347499


In [135]:
a_list = list(range(size))

print(type(a_list))

<class 'list'>


In [136]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")
print(timer_list.timeit(timeits)/timeits)

0.1425399142372556


In [17]:
x = np.array([23.23, 24.24])
print(x)

[ 23.23  24.24]


In [18]:
np.save('an_array', x)

In [19]:
np.load('an_array.npy')

array([ 23.23,  24.24])

In [20]:
np.savetxt('array.txt', X=x, delimiter=',')

In [21]:
!cat array.txt 

2.323000000000000043e+01
2.423999999999999844e+01


In [22]:
np.loadtxt('array.txt', delimiter=',')

array([ 23.23,  24.24])

In [2]:
import numpy as np

In [6]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(y2d.dot(x2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [7]:
print(x2d)
print(y2d)

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]


In [16]:
a1d = np.array([9,9])
b1d = np.array([10,10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


In [14]:
print(x2d.dot(a1d))
print()
print(np.dot(x2d,a1d))

[18 18]

[18 18]


In [25]:
ex1 = np.array([[11,12],[21,22]])
print(ex1)
print()
print(np.sum(ex1))

[[11 12]
 [21 22]]

66


In [26]:
print(np.sum(ex1, axis=0))

[32 34]


In [34]:
print(np.sum(ex1, axis=1))

[23 43]


In [29]:
ex2 = np.array([1,2,3,4])
print(ex2)

[1 2 3 4]


In [30]:
print(np.sum(ex2, axis=0))

10


In [35]:
ex3 = np.array([[[1,1],[2,2]],[[3,3],[4,4]]])
print(ex3)

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]


In [45]:
print(ex3[0][1][0])

2


In [36]:
print(np.sum(ex3, axis=0))

[[4 4]
 [6 6]]


In [37]:
print(np.sum(ex3, axis=1))

[[3 3]
 [7 7]]


In [39]:
print(np.sum(ex3, axis=2))

[[2 4]
 [6 8]]


In [46]:
x = np.random.randn(8)
x

array([ 0.58642323,  0.55129264,  0.70079631, -1.63970016,  0.49631049,
        0.51933338,  0.82783199,  0.06676564])

In [47]:
y = np.random.randn(8)
y

array([-0.61556337,  0.32534297,  0.60138979, -0.41261693, -0.70358219,
       -0.59846145, -0.39832815,  0.21238571])

In [48]:
np.maximum(x,y)

array([ 0.58642323,  0.55129264,  0.70079631, -0.41261693,  0.49631049,
        0.51933338,  0.82783199,  0.21238571])

In [49]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
 print(arr.reshape(2,3,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [55]:
ex1 = np.array([[11,12],[21,22]])
print(ex1)

[[11 12]
 [21 22]]


In [56]:
print(ex1.T)

[[11 21]
 [12 22]]


In [57]:
ex2 = arr.reshape(2,3,2)
print(ex2.T)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [60]:
x1 = np.array([1,2,3,4,5])
y1 = np.array([11,22,33,44,55])
filter = np.array([True,False,True,False,True])

print(x1)
print(y1)
print(filter)

[1 2 3 4 5]
[11 22 33 44 55]
[ True False  True False  True]


In [61]:
out = np.where(filter, x1,y1)
print(out)

[ 1 22  3 44  5]


In [62]:
mat = np.random.randn(5,5)
mat

array([[ 0.33749734,  1.23587849,  1.50678189,  1.82396191,  0.05122551],
       [ 0.47781135, -1.14562046,  1.27072058,  1.924416  , -2.62102368],
       [-0.0715623 ,  0.37941563,  1.94741467, -1.04832244,  1.12951279],
       [-0.1259903 , -0.72568835,  0.21653888, -0.8042835 , -0.05939321],
       [-0.21291145,  1.80468597, -0.62434384, -0.17738019,  0.91786726]])

In [63]:
mat > 0.5

array([[False,  True,  True,  True, False],
       [False, False,  True,  True, False],
       [False, False,  True, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False,  True]], dtype=bool)

In [64]:
np.where(mat > 0.5,1000,-1)

array([[  -1, 1000, 1000, 1000,   -1],
       [  -1,   -1, 1000, 1000,   -1],
       [  -1,   -1, 1000,   -1, 1000],
       [  -1,   -1,   -1,   -1,   -1],
       [  -1, 1000,   -1,   -1, 1000]])

In [72]:
arr_bools = np.logical_not(np.array([False, False, False, False, False]))
arr_bools

array([ True,  True,  True,  True,  True], dtype=bool)

In [73]:
arr_bools.any()

True

In [74]:
arr_bools.all()

True

In [81]:
y = np.random.normal(size=[1,5])[0]
print(y)

[-0.14698823 -0.47447834  1.18099018  0.33119964 -1.60301544]


In [82]:
z = np.random.randint(low = 2, high=50, size=4)
print(z)

[47 45 11 18]


In [84]:
np.random.uniform(size=100)

array([ 0.8388551 ,  0.85547713,  0.74929351,  0.05985975,  0.67791874,
        0.23724915,  0.16340533,  0.17874317,  0.0287259 ,  0.0883116 ,
        0.87827992,  0.83857256,  0.66182576,  0.16363669,  0.97926861,
        0.97609811,  0.27995219,  0.32137733,  0.28868985,  0.3997528 ,
        0.42195164,  0.11870507,  0.09335885,  0.05678715,  0.91156548,
        0.8008019 ,  0.36412062,  0.66445334,  0.86626011,  0.9101861 ,
        0.73095872,  0.93745819,  0.00755383,  0.23086002,  0.77875059,
        0.59293685,  0.84536345,  0.74465542,  0.16529268,  0.01502146,
        0.28500886,  0.45768708,  0.96914666,  0.02457461,  0.85812511,
        0.97594936,  0.73234051,  0.70243942,  0.66758968,  0.86105187,
        0.85890375,  0.80457333,  0.37115421,  0.35628837,  0.47584903,
        0.60973787,  0.74393917,  0.78082905,  0.03268663,  0.75281766,
        0.05561196,  0.14649388,  0.28922749,  0.84090518,  0.31484107,
        0.5208289 ,  0.71422426,  0.02971047,  0.66450473,  0.45

In [86]:
np.random.normal(size=5)

array([ 1.43684342,  0.45195784,  0.7880297 , -0.30184096,  0.83706513])

In [87]:
k = np.random.randint(low=2,high=50,size = (2,2))
print(k)
print()

m = np.random.randint(low=2,high=50,size = (2,2))
print(m)

[[42  7]
 [21 10]]

[[12 20]
 [49 38]]


In [88]:
np.vstack((k,m))

array([[42,  7],
       [21, 10],
       [12, 20],
       [49, 38]])

In [89]:
np.hstack((k,m))

array([[42,  7, 12, 20],
       [21, 10, 49, 38]])

In [90]:
np.vsplit(k,2)

[array([[42,  7]]), array([[21, 10]])]

In [93]:
print(np.hsplit(k,2)[0],np.hsplit(k,2)[1])

[[42]
 [21]] [[ 7]
 [10]]


In [94]:
np.concatenate([k,m],axis = 0)

array([[42,  7],
       [21, 10],
       [12, 20],
       [49, 38]])

In [95]:
np.concatenate([k,m],axis = 1)

array([[42,  7, 12, 20],
       [21, 10, 49, 38]])

In [2]:
import numpy as np
a = np.array([2, 3])
b1 = np.array([1])
b2 = 1 

In [3]:
a+b1

array([3, 4])

In [4]:
a+b2

array([3, 4])